// ─── IMAGE IMPORTS – RESTORATIVE ───
import img_r01 from '../../assets/restorative/1_Esthetic_Diastema_Management.jpeg'
import img_r02 from '../../assets/restorative/2_diastema_closure.jpeg'
import img_r03 from '../../assets/restorative/3_Anterior_Teeth.jpeg'
import img_r04 from '../../assets/restorative/4_Class_II_Composite_Partial_Caries_Removal.jpeg'
import img_r05 from '../../assets/restorative/5_Class_II_Composite_Restoration.jpeg'
import img_r06 from '../../assets/restorative/6_Endodontic_Treatment .jpeg'
import img_r07 from '../../assets/restorative/7_Multiple_Class_V.jpeg'
import img_r08 from '../../assets/restorative/8_Fractured_Tooth.jpeg'
import img_r09 from '../../assets/restorative/9_Class_III_IV.jpeg'
import img_r10 from '../../assets/restorative/10_MOD_Composite.jpeg'
import img_e01 from '../../assets/endodontics/1_Endodontic_Treatment_Maxillary_First_Premolar.jpeg'
import img_e02 from '../../assets/endodontics/2_Endodontic_Treatment_Mandibular_Second_Premolar.jpeg'
import img_pe01 from '../../assets/periodontics/1_full_mouth_sdcalling_plaque .jpeg'
import img_pe02 from '../../assets/periodontics/2_full_mouth_sdcalling_supragingival .jpeg'
import img_pe03 from '../../assets/periodontics/3_lower_anterior_scalling.jpeg'

// ─── IMAGE IMPORTS – PROSTHODONTICS ───
import img_p01 from '../../assets/Prosthodontics/1_zirconia_bridge.jpeg'
import img_p02 from '../../assets/Prosthodontics/2_Complete_Denture_Rehabilitation _ Case_1.jpeg'
import img_p03 from '../../assets/Prosthodontics/3_Complete_Denture_Rehabilitation _ Case_2.jpeg'
import img_p04 from '../../assets/Prosthodontics/4_single_crown.jpeg'

// =============================================
// CLINICAL DATA – Dr. Wahba Dental Portfolio
// =============================================

export const SPECIALTIES = [
  {
    id: 'restorative',
    icon: '🦷',
    name: 'Restorative Dentistry',
    nameAr: 'طب الأسنان الترميمي',
    cases: 30,
    desc: 'Direct composite restorations, diastema closures, anterior rehabilitations, and conservative cavity management to restore function and esthetics.',
    color: '#1E5FA8',
  },
  {
    id: 'endodontics',
    icon: '🔬',
    name: 'Endodontics',
    nameAr: 'علاج الجذور',
    cases: 7,
    desc: 'Root canal treatments, retreatments, and periapical surgeries performed under magnification using rotary instruments and warm obturation techniques.',
    color: '#0F2747',
  },
  {
    id: 'prosthodontics',
    icon: '👑',
    name: 'Prosthodontics',
    nameAr: 'التعويضات السنية',
    cases: 7,
    desc: 'Fixed and removable prosthetics including porcelain-fused-to-metal crowns, full-ceramic restorations, implant-supported prostheses, and complete dentures.',
    color: '#C9A84C',
  },
  {
    id: 'periodontology',
    icon: '🌱',
    name: 'Periodontology',
    nameAr: 'أمراض اللثة',
    cases: 15,
    desc: 'Management of periodontal diseases including scaling and root planing, flap surgeries, bone regeneration, and soft tissue grafting procedures.',
    color: '#2D6A4F',
  },
]

export const CASES = [
  // ── RESTORATIVE ──
  {
    id: 'r-01',
    specialtyId: 'restorative',
    title: 'Esthetic Diastema Management',
    treatmentType: 'Direct Composite Restoration',
    coverImage: img_r01,
    summary: 'A minimally invasive direct composite technique was used to close the midline spacing and improve smile esthetics. Careful shade selection and contouring were carried out to ensure seamless integration with the adjacent teeth.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, bonding agent, shade guide',
    technique: 'Freehand direct composite layering with shade matching',
    chiefComplaint: 'The patient presented with a noticeable midline diastema causing esthetic concerns and reduced smile confidence.',
    diagnosis: 'Midline diastema requiring esthetic closure with a minimally invasive direct composite approach.',
    treatmentPlan: 'Close the midline diastema using freehand direct composite, focusing on accurate shade selection, proper contouring, and seamless integration with adjacent teeth.',
    timeline: [
      { step: 1, title: 'Shade Selection & Planning', image: img_r01, desc: 'Careful shade selection was performed to match the natural dentition and plan the composite layering strategy for optimal esthetic integration.' },
      { step: 2, title: 'Composite Application', image: img_r01, desc: 'Direct composite resin was incrementally applied and sculpted to close the midline spacing while maintaining natural tooth proportions and contour.' },
      { step: 3, title: 'Finishing & Polishing', image: img_r01, desc: 'The restoration was finished and polished to achieve a smooth, natural-looking surface that blends seamlessly with the adjacent teeth.' },
    ],
    beforeImage: img_r01,
    afterImage: img_r01,
    notes: 'This case demonstrates how a conservative direct composite approach can achieve excellent esthetic outcomes for diastema closure without any tooth preparation, preserving natural enamel structure.',
  },
  {
    id: 'r-02',
    specialtyId: 'restorative',
    title: 'Diastema Closure',
    treatmentType: 'Direct Composite Restoration',
    coverImage: img_r02,
    summary: 'Direct composite restoration was performed to conservatively close the anterior spacing while preserving natural tooth structure. The treatment focused on achieving proper tooth proportions, symmetry, and a harmonious smile with a natural esthetic outcome.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, bonding agent, polishing discs',
    technique: 'Additive direct composite technique with symmetry analysis',
    chiefComplaint: 'The patient sought treatment for anterior spacing that affected the appearance and symmetry of the smile.',
    diagnosis: 'Anterior diastema with esthetic impact requiring conservative direct composite closure.',
    treatmentPlan: 'Perform additive composite restoration to close the anterior spacing, restore proper tooth proportions and symmetry, and achieve a harmonious natural smile.',
    timeline: [
      { step: 1, title: 'Smile Analysis & Shade Match', image: img_r02, desc: 'A thorough smile analysis was conducted to assess tooth proportions and symmetry before selecting the appropriate composite shade.' },
      { step: 2, title: 'Direct Composite Buildup', image: img_r02, desc: 'Composite resin was applied additively to close the diastema while carefully maintaining tooth proportions and restoring smile symmetry.' },
      { step: 3, title: 'Contouring & Polish', image: img_r02, desc: 'Final contouring and polishing produced a smooth, natural result that harmonizes with the rest of the dentition.' },
    ],
    beforeImage: img_r02,
    afterImage: img_r02,
    notes: 'Diastema closure with direct composite is a highly conservative and predictable technique when proper proportional analysis and layering are applied. The result preserves natural tooth structure while significantly improving smile esthetics.',
  },
  {
    id: 'r-03',
    specialtyId: 'restorative',
    title: 'Anterior Teeth Rehabilitation',
    treatmentType: 'Direct Composite + Removable Partial Denture',
    coverImage: img_r03,
    summary: 'Comprehensive rehabilitation of the anterior teeth was performed using direct composite restorations to restore esthetics and function. The treatment was completed with a removable partial denture to replace the missing teeth, providing improved function, smile harmony, and overall patient satisfaction.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, bonding agent, acrylic removable partial denture',
    technique: 'Direct composite rehabilitation combined with removable prosthetic replacement',
    chiefComplaint: 'The patient presented with damaged anterior teeth and missing teeth affecting both function and smile esthetics.',
    diagnosis: 'Anterior teeth requiring direct composite rehabilitation with partial edentulism managed by a removable partial denture.',
    treatmentPlan: 'Restore existing anterior teeth with direct composite restorations to re-establish esthetics and function, then fabricate a removable partial denture to replace missing teeth and complete the rehabilitation.',
    timeline: [
      { step: 1, title: 'Composite Restorations', image: img_r03, desc: 'Direct composite restorations were placed on the damaged anterior teeth to restore their form, function, and esthetic appearance.' },
      { step: 2, title: 'Impression & Denture Planning', image: img_r03, desc: 'Impressions were taken and the removable partial denture was planned to replace missing teeth and complete the anterior arch rehabilitation.' },
      { step: 3, title: 'Prosthetic Delivery & Adjustment', image: img_r03, desc: 'The removable partial denture was delivered, adjusted for fit and occlusion, and the patient was instructed on proper care and maintenance.' },
    ],
    beforeImage: img_r03,
    afterImage: img_r03,
    notes: 'This case highlights the importance of combining direct restorative techniques with prosthetic solutions in comprehensive rehabilitation. Treating existing teeth before prosthetic placement ensures a harmonious and stable final result.',
  },
  {
    id: 'r-04',
    specialtyId: 'restorative',
    title: 'Class II Composite with Partial Caries Removal',
    treatmentType: 'Conservative Class II Composite (PCR)',
    coverImage: img_r04,
    summary: 'A conservative Class II composite restoration was performed using a partial caries removal (PCR) approach to minimize the risk of pulp exposure while preserving tooth vitality. The cavity was restored with direct composite, achieving a functional restoration with proper proximal contact and anatomical contour.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, selective caries excavation bur, bonding agent, matrix system',
    technique: 'Partial caries removal (PCR) with direct Class II composite restoration',
    chiefComplaint: 'The patient presented with a deep proximal cavity approaching the pulp, requiring a conservative management approach to preserve tooth vitality.',
    diagnosis: 'Deep Class II carious lesion in proximity to the pulp, managed with partial caries removal to avoid pulp exposure while restoring tooth structure.',
    treatmentPlan: 'Apply selective caries removal to preserve the innermost layer of affected dentin over the pulp, then restore the cavity with a direct Class II composite restoration with proper proximal contact and anatomical form.',
    timeline: [
      { step: 1, title: 'Selective Caries Removal', image: img_r04, desc: 'Caries was selectively removed, leaving the innermost affected dentin layer over the pulp to avoid pulp exposure and preserve vitality.' },
      { step: 2, title: 'Matrix Placement & Bonding', image: img_r04, desc: 'A sectional matrix system was placed to restore the proximal wall, and bonding agent was applied to optimize composite adhesion.' },
      { step: 3, title: 'Composite Restoration', image: img_r04, desc: 'Direct composite was incrementally placed and cured to restore the cavity with proper proximal contact, marginal adaptation, and anatomical contour.' },
    ],
    beforeImage: img_r04,
    afterImage: img_r04,
    notes: 'Partial caries removal is a biologically conservative strategy that prioritizes pulp preservation in deep lesions. This case reinforces the importance of evidence-based caries management to avoid unnecessary pulp exposure while achieving a durable restoration.',
  },
  {
    id: 'r-05',
    specialtyId: 'restorative',
    title: 'Class II Composite Restoration',
    treatmentType: 'Direct Class II Composite',
    coverImage: img_r05,
    summary: 'A direct Class II composite restoration was performed to restore proximal contact, anatomical contour, and occlusal function while preserving sound tooth structure. Careful attention was given to achieving proper adaptation, contour, and esthetic integration with the natural dentition.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, bonding agent, sectional matrix system, wedge',
    technique: 'Incremental direct Class II composite with sectional matrix',
    chiefComplaint: 'The patient presented with a proximal carious lesion requiring restoration to recover function and proximal contact with the adjacent tooth.',
    diagnosis: 'Class II carious lesion requiring direct composite restoration to restore proximal contact and occlusal anatomy.',
    treatmentPlan: 'Remove caries conservatively, place a sectional matrix to guide proximal wall formation, and restore with direct composite using an incremental technique for optimal adaptation and anatomical form.',
    timeline: [
      { step: 1, title: 'Caries Removal & Cavity Preparation', image: img_r05, desc: 'Caries was removed conservatively while preserving maximum healthy tooth structure to support the composite restoration.' },
      { step: 2, title: 'Matrix Placement & Composite Layering', image: img_r05, desc: 'A sectional matrix system was used to rebuild the proximal wall, and composite was incrementally placed to restore proper contour and contact.' },
      { step: 3, title: 'Finishing, Polishing & Occlusal Check', image: img_r05, desc: 'The restoration was finished and polished, and occlusal contacts were verified to ensure functional harmony with the opposing dentition.' },
    ],
    beforeImage: img_r05,
    afterImage: img_r05,
    notes: 'Achieving tight proximal contact and proper contour in Class II restorations requires careful matrix system selection and composite layering strategy. This case demonstrates a predictable technique for restoring posterior proximal cavities with direct composite.',
  },
  {
    id: 'r-06',
    specialtyId: 'restorative',
    title: 'Endodontic Treatment with Direct Composite Overlay',
    treatmentType: 'EverX-Reinforced Composite Overlay',
    coverImage: img_r06,
    summary: 'Following successful endodontic treatment, the tooth was restored with an EverX-reinforced direct composite overlay to enhance fracture resistance and restore function. A valuable learning experience in balancing function with ideal morphology.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Multiple visits',
    visits: 2,
    materials: 'EverX Posterior fiber-reinforced composite, nanohybrid composite, bonding agent',
    technique: 'EverX fiber-reinforced composite base with direct overlay',
    chiefComplaint: 'The tooth had undergone endodontic treatment and required a definitive restoration to protect it from fracture and restore occlusal function.',
    diagnosis: 'Endodontically treated tooth with compromised structure requiring a reinforced direct composite overlay to enhance fracture resistance.',
    treatmentPlan: 'Restore the endodontically treated tooth with an EverX fiber-reinforced composite base followed by a direct composite overlay, balancing structural reinforcement with functional and morphological requirements.',
    timeline: [
      { step: 1, title: 'Post-Endodontic Assessment', image: img_r06, desc: 'The tooth was assessed following endodontic treatment to plan the most appropriate restorative approach based on remaining tooth structure.' },
      { step: 2, title: 'EverX Base Placement', image: img_r06, desc: 'An EverX fiber-reinforced composite base was placed to enhance fracture resistance and provide a strong foundation for the final overlay.' },
      { step: 3, title: 'Composite Overlay & Finishing', image: img_r06, desc: 'The direct composite overlay was applied, contoured, and polished to restore occlusal morphology and functional harmony.' },
    ],
    beforeImage: img_r06,
    afterImage: img_r06,
    notes: 'This case was an important learning experience in post-endodontic restoration. EverX-reinforced composites significantly improve fracture resistance in endodontically treated teeth, but achieving ideal morphology alongside proper reinforcement requires careful planning and material understanding.',
  },
  {
    id: 'r-07',
    specialtyId: 'restorative',
    title: 'Multiple Class V Composite Restorations',
    treatmentType: 'Class V Direct Composite',
    coverImage: img_r07,
    summary: 'Multiple Class V cervical lesions were restored using direct composite resin to re-establish tooth structure, improve esthetics, and reduce sensitivity. Careful attention was given to marginal adaptation, contour, and finishing to ensure durable and natural-looking restorations.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Nanohybrid composite resin, bonding agent, cervical matrix',
    technique: 'Direct Class V composite placement with cervical adaptation and polishing',
    chiefComplaint: 'The patient presented with multiple cervical lesions causing sensitivity and esthetic concerns at the gingival margin of several teeth.',
    diagnosis: 'Multiple Class V cervical carious lesions or non-carious cervical lesions requiring direct composite restorations for structural and esthetic rehabilitation.',
    treatmentPlan: 'Restore each cervical lesion with direct composite resin, ensuring optimal marginal adaptation, cervical contour, and smooth polishing for durability and natural appearance.',
    timeline: [
      { step: 1, title: 'Isolation & Surface Preparation', image: img_r07, desc: 'The teeth were isolated and cervical lesions were prepared to receive composite restoration, with careful attention to gingival margin management.' },
      { step: 2, title: 'Bonding & Composite Placement', image: img_r07, desc: 'Bonding agent was applied and composite was placed incrementally to fill each cervical lesion with good marginal adaptation and proper cervical contour.' },
      { step: 3, title: 'Finishing, Polishing & Sensitivity Check', image: img_r07, desc: 'Restorations were finished and polished to create smooth, natural-looking surfaces, and sensitivity was assessed to confirm satisfactory outcomes.' },
    ],
    beforeImage: img_r07,
    afterImage: img_r07,
    notes: 'Class V restorations present a unique challenge due to the cervical location, proximity to the gingiva, and the high-stress area they occupy. Proper isolation, bonding technique, and surface finishing are critical for long-term success and patient comfort.',
  },
  {
    id: 'r-08',
    specialtyId: 'restorative',
    title: 'Fractured Tooth Restoration',
    treatmentType: 'Direct Composite Restoration',
    coverImage: img_r08,
    summary: 'A fractured anterior tooth was conservatively restored using a direct composite restoration to re-establish its form, function, and esthetics. Due to the presence of enamel hypoplasia, a slight shade mismatch was unavoidable; however, the restoration provided a satisfactory functional and esthetic result.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, bonding agent, shade guide, polishing paste',
    technique: 'Freehand direct composite buildup for fractured anterior tooth',
    chiefComplaint: 'The patient presented with a fractured anterior tooth causing esthetic concern and affecting the overall smile appearance.',
    diagnosis: 'Fractured anterior tooth with enamel hypoplasia requiring conservative direct composite restoration to restore form, function, and esthetics.',
    treatmentPlan: 'Restore the fractured tooth with a direct composite using freehand buildup technique, selecting the best shade match possible despite the enamel hypoplasia, to achieve a functional and esthetically satisfactory outcome.',
    timeline: [
      { step: 1, title: 'Fracture Assessment & Shade Selection', image: img_r08, desc: 'The fracture extent was assessed and the optimal composite shade was selected, accounting for the existing enamel hypoplasia present on the tooth.' },
      { step: 2, title: 'Composite Buildup', image: img_r08, desc: 'The fractured tooth was rebuilt using freehand composite layering, re-establishing incisal edge, proximal contours, and labial surface form.' },
      { step: 3, title: 'Finishing & Polishing', image: img_r08, desc: 'The restoration was finished and polished to provide a smooth, natural surface, achieving a satisfactory esthetic and functional result despite the inherent shade limitation.' },
    ],
    beforeImage: img_r08,
    afterImage: img_r08,
    notes: 'This case presented a clinical challenge due to enamel hypoplasia, which limited perfect shade integration. It reinforced the importance of thorough pre-treatment communication with the patient regarding realistic esthetic expectations while still delivering a functional and esthetically acceptable restoration.',
  },
  {
    id: 'r-09',
    specialtyId: 'restorative',
    title: 'Class III/IV Composite Restoration',
    treatmentType: 'Direct Composite (Class III/IV)',
    coverImage: img_r09,
    summary: 'A direct composite restoration was performed to restore a tooth presenting with combined Class III and Class IV defects. Emphasis was placed on conservative tooth preparation, proper shade selection, and restoration of proximal contour and incisal anatomy.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Enamel and dentin composite resin, bonding agent, interproximal wedge',
    technique: 'Layered direct composite for combined Class III/IV restoration',
    chiefComplaint: 'The patient presented with a proximal and incisal defect on an anterior tooth, affecting both smile esthetics and incisal function.',
    diagnosis: 'Combined Class III and Class IV defect requiring layered direct composite restoration to restore proximal form and incisal anatomy.',
    treatmentPlan: 'Restore the combined Class III/IV defect using a layered composite technique, focusing on conservative preparation, accurate shade selection, and restoring natural proximal contour and incisal edge anatomy.',
    timeline: [
      { step: 1, title: 'Assessment & Shade Selection', image: img_r09, desc: 'The combined defect was assessed and shade selection was performed using enamel and dentin shades to plan a layered composite approach.' },
      { step: 2, title: 'Layered Composite Restoration', image: img_r09, desc: 'Dentin and enamel composite layers were applied to restore the proximal contour and re-establish the incisal edge anatomy with natural-looking depth and translucency.' },
      { step: 3, title: 'Surface Finishing & Occlusal Check', image: img_r09, desc: 'The restoration was finished, polished, and occlusal contacts were verified to ensure functional comfort and esthetic integration.' },
    ],
    beforeImage: img_r09,
    afterImage: img_r09,
    notes: 'Class III/IV restorations require a clear understanding of anterior tooth anatomy and layering techniques. This case demonstrated how a careful shade stratification approach can restore proximal and incisal form with excellent esthetic integration in a single visit.',
  },
  {
    id: 'r-10',
    specialtyId: 'restorative',
    title: 'MOD Composite Restoration',
    treatmentType: 'MOD Composite (PCR Approach)',
    coverImage: img_r10,
    summary: 'A deep MOD lesion was managed using a partial caries removal (PCR) approach to preserve pulp vitality and reduce the risk of pulp exposure. The cavity was restored with direct composite, providing a functional restoration with proper proximal contact, marginal adaptation, and anatomical form.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Composite resin, bonding agent, dual sectional matrix system, selective caries excavation bur',
    technique: 'Partial caries removal with direct MOD composite restoration',
    chiefComplaint: 'The patient presented with a deep multisurface carious lesion involving the mesial, occlusal, and distal surfaces of a posterior tooth, requiring careful management to preserve pulp vitality.',
    diagnosis: 'Deep MOD carious lesion in a posterior tooth managed with partial caries removal to protect the pulp and restore with direct composite.',
    treatmentPlan: 'Apply partial caries removal to the deepest aspect of the lesion, place a dual sectional matrix to restore both proximal surfaces, and restore the MOD cavity with direct composite to achieve proper contacts, marginal adaptation, and anatomical occlusal form.',
    timeline: [
      { step: 1, title: 'Partial Caries Removal', image: img_r10, desc: 'Selective caries removal was performed, leaving the deepest layer of affected dentin over the pulp to minimize pulp exposure risk while eliminating active caries.' },
      { step: 2, title: 'Matrix System & Proximal Wall Rebuild', image: img_r10, desc: 'A dual sectional matrix system was placed to guide the rebuilding of both proximal surfaces with proper contour and tight interproximal contacts.' },
      { step: 3, title: 'Composite Restoration & Occlusal Anatomy', image: img_r10, desc: 'The MOD cavity was restored with direct composite using an incremental technique, restoring occlusal anatomy, marginal ridges, and functional form.' },
    ],
    beforeImage: img_r10,
    afterImage: img_r10,
    notes: 'MOD restorations are among the most demanding direct composite procedures due to the extensive cavity design and the need to restore two proximal contacts simultaneously. Partial caries removal in this case was critical to preserve pulp vitality while achieving a biologically and functionally sound restoration.',
  },

  // ── ENDODONTICS ──
  {
    id: 'e-01',
    specialtyId: 'endodontics',

    title: 'Endodontic Treatment of a Maxillary First Premolar',
    treatmentType: 'Non-Surgical Root Canal Treatment',
    coverImage: img_e01,
    summary: 'Non-surgical root canal treatment was successfully performed on a maxillary first premolar with two canals. Careful canal location, cleaning and shaping, and three-dimensional obturation were carried out to achieve a predictable biological and functional outcome.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Rotary files, irrigants, gutta-percha, endodontic sealer',
    technique: 'Two-canal cleaning, shaping, and three-dimensional obturation',
    chiefComplaint: 'The tooth required endodontic management to eliminate pulpal infection and preserve natural tooth structure.',
    diagnosis: 'Maxillary first premolar indicated for non-surgical root canal treatment with two canals.',
    treatmentPlan: 'Locate both canals accurately, determine working length, complete chemomechanical preparation, and obturate the canal system three-dimensionally.',
    timeline: [
      { step: 1, title: 'Canal Location', image: img_e01, desc: 'Careful access and canal location were performed to identify the two-canal anatomy of the maxillary first premolar.' },
      { step: 2, title: 'Cleaning and Shaping', image: img_e01, desc: 'The canals were cleaned, shaped, and irrigated to remove infected tissue and prepare the root canal system.' },
      { step: 3, title: 'Three-Dimensional Obturation', image: img_e01, desc: 'Obturation was completed to seal the prepared canal system and support a predictable biological and functional outcome.' },
    ],
    beforeImage: img_e01,
    afterImage: img_e01,
    notes: 'This case highlights the importance of careful canal identification and controlled obturation in maxillary premolar anatomy.',
  },
  {
    id: 'e-02',
    specialtyId: 'endodontics',

    title: 'Endodontic Treatment of a Mandibular Second Premolar',
    treatmentType: 'Non-Surgical Root Canal Treatment',
    coverImage: img_e02,
    summary: 'Non-surgical root canal treatment was performed on a mandibular second premolar to eliminate infection and preserve the natural tooth. The procedure included accurate working length determination, thorough cleaning and shaping, and three-dimensional obturation to achieve a predictable long-term outcome.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Rotary files, irrigants, gutta-percha, endodontic sealer',
    technique: 'Working length determination, canal preparation, and three-dimensional obturation',
    chiefComplaint: 'The tooth required root canal treatment to resolve infection while maintaining the natural premolar.',
    diagnosis: 'Mandibular second premolar indicated for non-surgical endodontic treatment.',
    treatmentPlan: 'Determine accurate working length, complete thorough cleaning and shaping, then obturate the canal system for long-term sealing.',
    timeline: [
      { step: 1, title: 'Working Length Determination', image: img_e02, desc: 'Working length was accurately determined to guide controlled instrumentation of the canal system.' },
      { step: 2, title: 'Cleaning and Shaping', image: img_e02, desc: 'The canal was thoroughly cleaned and shaped to remove infection and create a predictable preparation.' },
      { step: 3, title: 'Three-Dimensional Obturation', image: img_e02, desc: 'The canal was obturated three-dimensionally to preserve the tooth and support a stable long-term outcome.' },
    ],
    beforeImage: img_e02,
    afterImage: img_e02,
    notes: 'Accurate working length control and thorough canal preparation were central to preserving this mandibular premolar.',
  },

  // ── PROSTHODONTICS ──
  {
    id: 'p-01',
    specialtyId: 'prosthodontics',
    title: 'Zirconia Bridge',
    treatmentType: 'Fixed Dental Bridge (Full-Contour Zirconia)',
    coverImage: img_p01,
    summary: 'A full-contour zirconia fixed dental bridge was fabricated and delivered to replace the missing tooth/teeth while restoring function and esthetics. Careful attention was given to tooth preparation, marginal fit, occlusion, and shade selection to achieve a durable and natural-looking final restoration.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Multiple visits',
    visits: 3,
    materials: 'Full-contour zirconia, dental cement, shade guide',
    technique: 'Tooth preparation, digital impression, milled zirconia bridge, final cementation',
    chiefComplaint: 'The patient presented with a missing tooth/teeth requiring a fixed prosthetic solution to restore function and esthetics.',
    diagnosis: 'Missing tooth/teeth indicated for a fixed zirconia bridge to restore masticatory function and smile esthetics.',
    treatmentPlan: 'Prepare abutment teeth, take impressions, fabricate a full-contour zirconia bridge with proper shade matching, and deliver with final cementation ensuring correct occlusion and marginal fit.',
    timeline: [
      { step: 1, title: 'Tooth Preparation', image: img_p01, desc: 'Abutment teeth were carefully prepared following principles of occlusal reduction, taper, and adequate ferrule to support the zirconia bridge framework.' },
      { step: 2, title: 'Impression & Shade Selection', image: img_p01, desc: 'Accurate impressions were taken and shade selection was carried out to guide the laboratory fabrication of the natural-looking final restoration.' },
      { step: 3, title: 'Bridge Delivery & Cementation', image: img_p01, desc: 'The full-contour zirconia bridge was tried in, marginal fit and occlusion were verified, and final cementation was performed to deliver a durable functional restoration.' },
    ],
    beforeImage: img_p01,
    afterImage: img_p01,
    notes: 'Full-contour zirconia bridges offer excellent strength, biocompatibility, and esthetics, making them a reliable long-term fixed prosthetic option. Precision in tooth preparation and marginal fit are key to predictable outcomes.',
  },
  {
    id: 'p-02',
    specialtyId: 'prosthodontics',
    title: 'Complete Denture Rehabilitation – Case 1',
    treatmentType: 'Complete Denture Fabrication',
    coverImage: img_p02,
    summary: "Complete dentures were fabricated to restore the patient's oral function, facial support, and esthetics. Careful attention was given to primary and final impressions, jaw relation records, tooth arrangement, and denture delivery to achieve comfort, stability, and patient satisfaction.",
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Multiple visits',
    visits: 5,
    materials: 'Acrylic resin, denture teeth, impression materials, wax',
    technique: 'Conventional complete denture fabrication with primary and final impressions, jaw relation records, and tooth arrangement',
    chiefComplaint: 'The patient presented as fully edentulous, requiring complete dentures to restore masticatory function, facial support, and esthetics.',
    diagnosis: 'Complete edentulism requiring conventional complete denture construction to restore function, facial support, and patient quality of life.',
    treatmentPlan: 'Fabricate conventional complete dentures following a systematic clinical and laboratory workflow including primary impressions, final impressions, jaw relation records, try-in, and denture delivery.',
    timeline: [
      { step: 1, title: 'Primary & Final Impressions', image: img_p02, desc: 'Primary and final impressions were taken to capture the full extent of the denture-bearing area, ensuring proper border extension and accuracy.' },
      { step: 2, title: 'Jaw Relation Records & Tooth Arrangement', image: img_p02, desc: 'Jaw relations were carefully recorded and denture teeth were arranged to achieve balanced occlusion and optimal facial support and esthetics.' },
      { step: 3, title: 'Denture Delivery & Patient Satisfaction', image: img_p02, desc: 'The completed dentures were delivered with occlusal adjustments and hygiene instructions, achieving comfort, stability, and patient satisfaction.' },
    ],
    beforeImage: img_p02,
    afterImage: img_p02,
    notes: 'Complete denture fabrication requires a thorough understanding of edentulous anatomy, border extension, and occlusal principles. Patient comfort and satisfaction are the primary clinical benchmarks for success.',
  },
  {
    id: 'p-03',
    specialtyId: 'prosthodontics',
    title: 'Complete Denture Rehabilitation – Case 2',
    treatmentType: 'Conventional Complete Denture',
    coverImage: img_p03,
    summary: 'Conventional complete dentures were constructed following a systematic clinical and laboratory workflow. The treatment focused on accurate border extension, balanced occlusion, retention, and esthetics to provide optimal function and improved quality of life for the patient.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Multiple visits',
    visits: 5,
    materials: 'Acrylic resin, denture teeth, impression materials, occlusal registration materials',
    technique: 'Systematic clinical and laboratory workflow with focus on border extension, balanced occlusion, and retention',
    chiefComplaint: 'The patient required complete dentures to replace all missing teeth and restore proper oral function, aesthetics, and quality of life.',
    diagnosis: 'Complete edentulism requiring a systematic denture fabrication approach focusing on retention, border extension, and balanced occlusion.',
    treatmentPlan: 'Construct conventional complete dentures using a step-by-step clinical protocol with emphasis on accurate impressions, correct border molding, balanced occlusion, and esthetic tooth arrangement.',
    timeline: [
      { step: 1, title: 'Border Extension & Final Impressions', image: img_p03, desc: 'Careful border molding and final impression techniques were used to achieve accurate denture border extension and capture the functional anatomy of the edentulous ridges.' },
      { step: 2, title: 'Balanced Occlusion & Esthetics', image: img_p03, desc: 'Jaw relation records were taken and teeth were arranged to achieve balanced occlusion and harmonious facial esthetics with proper support.' },
      { step: 3, title: 'Delivery & Retention Check', image: img_p03, desc: 'Dentures were delivered following verification of retention, stability, and occlusal balance, resulting in improved function and patient quality of life.' },
    ],
    beforeImage: img_p03,
    afterImage: img_p03,
    notes: 'This case reinforces the importance of following a systematic clinical and laboratory workflow to achieve well-fitting complete dentures with balanced occlusion and optimal patient comfort.',
  },
  {
    id: 'p-04',
    specialtyId: 'prosthodontics',
    title: 'Single Crown Restoration',
    treatmentType: 'Full-Coverage Single Crown',
    coverImage: img_p04,
    summary: 'A full-coverage single crown was fabricated to restore a structurally compromised tooth, providing optimal function, strength, and esthetics. The treatment included tooth preparation, digital impression, crown fabrication, and final cementation. The final restoration achieved proper marginal adaptation, occlusion, and shade matching, resulting in a functional and natural-looking outcome.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Multiple visits',
    visits: 2,
    materials: 'Full-coverage crown material, dental cement, shade guide',
    technique: 'Tooth preparation, impression, crown fabrication, and final cementation with occlusal verification',
    chiefComplaint: 'The patient presented with a structurally compromised tooth requiring a full-coverage crown to restore its function, strength, and appearance.',
    diagnosis: 'Structurally compromised tooth indicated for full-coverage single crown to restore function, prevent fracture, and achieve esthetic integration.',
    treatmentPlan: 'Prepare the tooth for full-coverage crown, take impressions, fabricate the crown with proper shade selection and marginal accuracy, and deliver with final cementation ensuring correct occlusion and adaptation.',
    timeline: [
      { step: 1, title: 'Tooth Preparation', image: img_p04, desc: 'The tooth was prepared for full-coverage restoration following principles of adequate reduction, axial taper, and margin placement for optimal crown fit.' },
      { step: 2, title: 'Impression & Crown Fabrication', image: img_p04, desc: 'Accurate impressions were taken and shade selection was performed to guide fabrication of a crown with proper contour, marginal adaptation, and natural appearance.' },
      { step: 3, title: 'Final Cementation & Occlusal Verification', image: img_p04, desc: 'The crown was seated, marginal adaptation was verified, occlusal contacts were adjusted, and final cementation was performed to complete the restoration.' },
    ],
    beforeImage: img_p04,
    afterImage: img_p04,
    notes: 'Full-coverage single crowns remain one of the most versatile fixed prosthetic options for restoring compromised teeth. Precision in preparation design, impression accuracy, and occlusal verification are critical for long-term success.',
  },

  // ── PERIODONTOLOGY ──
  {
    id: 'pe-01',
    specialtyId: 'periodontology',

    title: 'Full Mouth Scaling',
    treatmentType: 'Full Mouth Scaling',
    coverImage: img_pe01,
    summary: 'Full mouth scaling was performed to remove plaque and calculus deposits from all teeth, improving periodontal health and reducing gingival inflammation. The procedure was completed with polishing and personalized oral hygiene instructions to support long-term periodontal maintenance.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Ultrasonic scaler, periodontal hand instruments, polishing paste',
    technique: 'Full-mouth supragingival and subgingival scaling with polishing',
    chiefComplaint: 'The patient presented with plaque and calculus accumulation affecting periodontal health.',
    diagnosis: 'Generalized plaque and calculus deposits associated with gingival inflammation.',
    treatmentPlan: 'Perform full-mouth scaling, polish all tooth surfaces, and provide personalized oral hygiene instructions for maintenance.',
    timeline: [
      { step: 1, title: 'Plaque and Calculus Removal', image: img_pe01, desc: 'Full-mouth scaling was performed to remove plaque and calculus deposits from all teeth.' },
      { step: 2, title: 'Polishing', image: img_pe01, desc: 'The procedure was completed with polishing to create smoother tooth surfaces and support hygiene control.' },
      { step: 3, title: 'Maintenance Instructions', image: img_pe01, desc: 'Personalized oral hygiene instructions were provided to support long-term periodontal maintenance.' },
    ],
    beforeImage: img_pe01,
    afterImage: img_pe01,
    notes: 'The case demonstrates how full-mouth debridement, polishing, and hygiene reinforcement improve periodontal stability.',
  },
  {
    id: 'pe-02',
    specialtyId: 'periodontology',
    title: 'Full Mouth Scaling',
    treatmentType: 'Full Mouth Scaling',
    coverImage: img_pe02,
    summary: 'Full mouth scaling was performed to remove supragingival and subgingival plaque and calculus deposits, improving periodontal health and creating a clean oral environment. The treatment was followed by oral hygiene instructions to support long-term periodontal maintenance.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Ultrasonic scaler, periodontal hand instruments',
    technique: 'Supragingival and subgingival full-mouth scaling',
    chiefComplaint: 'The patient required periodontal debridement due to plaque and calculus deposits above and below the gingival margin.',
    diagnosis: 'Supragingival and subgingival plaque and calculus accumulation requiring full-mouth periodontal scaling.',
    treatmentPlan: 'Remove deposits from all teeth, create a clean oral environment, and reinforce daily oral hygiene measures.',
    timeline: [
      { step: 1, title: 'Supragingival Scaling', image: img_pe02, desc: 'Visible plaque and calculus deposits were removed from the tooth surfaces.' },
      { step: 2, title: 'Subgingival Scaling', image: img_pe02, desc: 'Subgingival deposits were carefully removed to improve periodontal tissue health.' },
      { step: 3, title: 'Oral Hygiene Support', image: img_pe02, desc: 'Oral hygiene instructions were provided to support long-term periodontal maintenance.' },
    ],
    beforeImage: img_pe02,
    afterImage: img_pe02,
    notes: 'This case focuses on establishing a clean oral environment through full-mouth supragingival and subgingival scaling.',
  },
  {
    id: 'pe-03',
    specialtyId: 'periodontology',
    title: 'Lower Anterior Scaling',
    treatmentType: 'Lower Anterior Scaling',
    coverImage: img_pe03,
    summary: 'Supragingival and subgingival scaling was performed on the lower anterior teeth to remove plaque and calculus deposits, improve periodontal health, and promote effective oral hygiene. The procedure resulted in cleaner tooth surfaces and healthier gingival tissues.',
    gender: 'Patient',
    patientAge: 'Adult',
    duration: 'Single visit',
    visits: 1,
    materials: 'Ultrasonic scaler, periodontal hand instruments',
    technique: 'Focused supragingival and subgingival scaling of lower anterior teeth',
    chiefComplaint: 'The lower anterior teeth showed localized plaque and calculus deposits requiring focused periodontal cleaning.',
    diagnosis: 'Localized supragingival and subgingival plaque and calculus deposits around the lower anterior teeth.',
    treatmentPlan: 'Perform focused lower anterior scaling, remove deposits, and reinforce hygiene techniques for the area.',
    timeline: [
      { step: 1, title: 'Lower Anterior Assessment', image: img_pe03, desc: 'The lower anterior region was assessed for plaque and calculus deposits.' },
      { step: 2, title: 'Focused Scaling', image: img_pe03, desc: 'Supragingival and subgingival scaling was performed to clean the lower anterior teeth.' },
      { step: 3, title: 'Gingival Health Support', image: img_pe03, desc: 'Cleaner tooth surfaces and improved hygiene access supported healthier gingival tissues.' },
    ],
    beforeImage: img_pe03,
    afterImage: img_pe03,
    notes: 'Focused scaling in the lower anterior region helped improve cleanliness, gingival tissue health, and oral hygiene effectiveness.',
  },
]

export function getCasesBySpecialty(specialtyId) {
  return CASES.filter((c) => c.specialtyId === specialtyId)
}

export function getCaseById(caseId) {
  return CASES.find((c) => c.id === caseId)
}

export function getSpecialtyById(specialtyId) {
  return SPECIALTIES.find((s) => s.id === specialtyId)
}
